import { FailureMode } from "@/lib/types";

export const failureModes: FailureMode[] = [
  {
    name: "Miscalibration",
    symptoms: ["High confidence wrong answers", "Low entropy outputs"],
    detectionSignals: ["ECE > threshold", "Confidence-error correlation"],
    tests: ["Reliability diagram", "Selective prediction eval"],
    mitigations: ["Temperature scaling", "Abstain thresholds", "Ensembles"],
    fallbackBehavior: "Escalate to human, return safe response",
    severity: "High",
    likelihood: "Possible",
  },
  {
    name: "Reward hacking",
    symptoms: ["Metric improves without value", "Proxy exploitation"],
    detectionSignals: ["Goal file diffs", "Metric/value divergence"],
    tests: ["Red-team for proxy gaming", "Diff check on goals"],
    mitigations: ["Signed goals", "Constraints + human eval"],
    fallbackBehavior: "Revert to last signed goal",
    severity: "High",
    likelihood: "Possible",
  },
  {
    name: "Tool misuse",
    symptoms: ["Unauthorized tool calls", "Missing justification"],
    detectionSignals: ["Tool risk>threshold", "No allowlist match"],
    tests: ["Adversarial tool prompts", "Rate-limit tests"],
    mitigations: ["Allowlists", "Justification requirement", "Rate limits"],
    fallbackBehavior: "Block tool and request justification",
    severity: "High",
    likelihood: "Likely",
  },
  {
    name: "Memory corruption",
    symptoms: ["Conflicting facts", "Unverifiable memory entries"],
    detectionSignals: ["Missing provenance", "Hash mismatch"],
    tests: ["Memory fuzz tests", "Audit snapshot checks"],
    mitigations: ["Hashes", "Quorum writes", "Snapshots"],
    fallbackBehavior: "Rollback to last clean snapshot",
    severity: "High",
    likelihood: "Possible",
  },
  {
    name: "Runaway self-modification",
    symptoms: ["Rapid policy churn", "Unapproved changes"],
    detectionSignals: ["Change rate > budget", "Unsigned configs"],
    tests: ["Self-mod update tests", "Approval flow tests"],
    mitigations: ["Budgets", "Approvals", "Feature flags"],
    fallbackBehavior: "Freeze updates, safe mode",
    severity: "High",
    likelihood: "Unlikely",
  },
  {
    name: "Deceptive alignment",
    symptoms: ["Behavior shifts in sandbox vs prod", "Hidden goals"],
    detectionSignals: ["Inconsistent responses", "Sandbox/prod diff"],
    tests: ["Hidden-goal tests", "Randomized audits"],
    mitigations: ["Cross-evals", "Random audits", "Transparency tools"],
    fallbackBehavior: "Quarantine model, human takeover",
    severity: "High",
    likelihood: "Unlikely",
  },
  {
    name: "Human trust miscalibration",
    symptoms: ["Over-reliance", "Under-use of safety buttons"],
    detectionSignals: ["Confidence UI ignored", "High override rate"],
    tests: ["Trust calibration studies", "UX A/B tests"],
    mitigations: ["Confidence-aware UI", "Education", "Forced confirmations"],
    fallbackBehavior: "Require human confirmation for risky flows",
    severity: "Medium",
    likelihood: "Likely",
  },
  {
    name: "Feedback-loop amplification",
    symptoms: ["Policy oscillations", "Metrics swing after small changes"],
    detectionSignals: ["High variance in metrics", "Rapid policy flips"],
    tests: ["Perturbation tests", "Sanity checks on telemetry"],
    mitigations: ["Hysteresis", "Sanity bounds", "Manual approval"],
    fallbackBehavior: "Revert to stable baseline",
    severity: "Medium",
    likelihood: "Possible",
  },
  {
    name: "Drift blindness",
    symptoms: ["Performance drops after shifts", "Late detection"],
    detectionSignals: ["PSI > threshold", "Input distribution shift"],
    tests: ["Drift simulators", "Alert tests"],
    mitigations: ["Drift monitors", "Canary rollback"],
    fallbackBehavior: "Rollback to previous model",
    severity: "Medium",
    likelihood: "Likely",
  },
  {
    name: "Logging without semantics",
    symptoms: ["Raw logs, no structure", "Hard debugging"],
    detectionSignals: ["Missing ids/policyVersion", "Unparseable events"],
    tests: ["Schema validation", "Replay drills"],
    mitigations: ["Structured telemetry", "Schema tests in CI"],
    fallbackBehavior: "Fallback to safe mode logging minimal data",
    severity: "Medium",
    likelihood: "Likely",
  },
  {
    name: "Postmortem theater",
    symptoms: ["Meetings without actions", "Repeated incidents"],
    detectionSignals: ["No new tests after incidents", "Untracked actions"],
    tests: ["Audit postmortem outputs", "Action item tracking"],
    mitigations: ["Action templates", "Owners + due dates"],
    fallbackBehavior: "Escalate to governance board",
    severity: "Medium",
    likelihood: "Possible",
  },
  {
    name: "Cost/latency blowup",
    symptoms: ["Budget overruns", "Slow responses"],
    detectionSignals: ["p95 latency>target", "Cost per request>budget"],
    tests: ["Load tests", "Budget monitors"],
    mitigations: ["Budgets", "Caching", "Tool throttling"],
    fallbackBehavior: "Degrade features, use cached responses",
    severity: "Medium",
    likelihood: "Possible",
  },
];
