import { GlossaryTerm } from "@/lib/types";

export const glossary: GlossaryTerm[] = [
  {
    term: "MCSE",
    definition: "Meta-Cognitive Systems Engineering; designs self-monitoring and governed cognition.",
    synonyms: ["meta-cognitive engineering"],
    relatedLessons: ["foundations-what-is-mcse"],
    examples: ["Adding meta-monitor and safety gates to an agent"],
    pitfalls: ["Treating MCSE as only logging"],
  },
  {
    term: "Meta-monitor",
    definition: "Component that observes signals about cognition and triggers actions.",
    synonyms: ["monitor"],
    relatedLessons: ["foundations-core-loops"],
    examples: ["Confidence watcher"],
    pitfalls: ["No thresholds"],
  },
  {
    term: "Meta-critic",
    definition: "Policy checker that critiques plans vs constraints.",
    synonyms: ["critic"],
    relatedLessons: ["architecture-reference"],
    examples: ["Rule-based critic"],
    pitfalls: ["No enforcement"],
  },
  {
    term: "Calibration",
    definition: "Alignment of confidence scores to actual correctness.",
    synonyms: ["reliability"],
    relatedLessons: ["control-confidence-calibration"],
    examples: ["Temperature scaling"],
    pitfalls: ["Ignoring class imbalance"],
  },
  {
    term: "ECE",
    definition: "Expected Calibration Error; average gap between confidence and correctness.",
    synonyms: [],
    relatedLessons: ["control-confidence-calibration"],
    examples: ["Bucketed reliability diagram"],
    pitfalls: ["Too few bins"],
  },
  {
    term: "Self-detection rate",
    definition: "Percent of errors caught by meta-monitor before user.",
    synonyms: ["self-catch rate"],
    relatedLessons: ["metrics-dictionary"],
    examples: ["70% of unsafe outputs blocked pre-user"],
    pitfalls: ["No baseline"],
  },
  {
    term: "Recovery time",
    definition: "Time from anomaly detection to safe state.",
    synonyms: ["MTTR for cognition"],
    relatedLessons: ["metrics-dictionary"],
    examples: ["5s to rollback"],
    pitfalls: ["Ignoring user impact"],
  },
  {
    term: "Drift",
    definition: "Distribution change between baseline and recent data.",
    synonyms: ["shift"],
    relatedLessons: ["control-drift-modeling"],
    examples: ["PSI 0.25 on inputs"],
    pitfalls: ["No alert thresholds"],
  },
  {
    term: "PSI",
    definition: "Population Stability Index for drift measurement.",
    synonyms: [],
    relatedLessons: ["control-drift-modeling"],
    examples: ["PSI >0.2 triggers rollback"],
    pitfalls: ["Small sample sizes"],
  },
  {
    term: "Jailbreak rate",
    definition: "Proportion of adversarial prompts that bypass safety.",
    synonyms: [],
    relatedLessons: ["metrics-dictionary"],
    examples: ["1% allowed after red-team"],
    pitfalls: ["Tiny test bank"],
  },
  {
    term: "Reward hacking",
    definition: "Optimizing proxy metrics instead of true goals.",
    synonyms: ["specification gaming"],
    relatedLessons: ["failure-reward-hacking"],
    examples: ["Maximizing ticket closure by replying nonsense"],
    pitfalls: ["Weak constraints"],
  },
  {
    term: "Goal drift",
    definition: "Goals change without approval or awareness.",
    synonyms: [],
    relatedLessons: ["failure-reward-hacking"],
    examples: ["Editing goal file in prod"],
    pitfalls: ["No signing"],
  },
  {
    term: "Tool risk",
    definition: "Relative risk of a tool based on capability and blast radius.",
    synonyms: [],
    relatedLessons: ["architecture-tooling-layer"],
    examples: ["Prod DB risk 0.9"],
    pitfalls: ["No allowlist"],
  },
  {
    term: "Escalation matrix",
    definition: "Mapping from signals to owners and actions.",
    synonyms: ["playbook"],
    relatedLessons: ["control-escalation-patterns"],
    examples: ["Drift>0.2 -> rollback"],
    pitfalls: ["Missing owners"],
  },
  {
    term: "Abstain policy",
    definition: "Rules for declining to answer when confidence/risk is poor.",
    synonyms: ["refusal policy"],
    relatedLessons: ["control-confidence-calibration"],
    examples: ["Confidence<0.3 => escalate"],
    pitfalls: ["Over-abstain"],
  },
  {
    term: "Selective prediction",
    definition: "Model only answers when confident enough.",
    synonyms: [],
    relatedLessons: ["control-confidence-calibration"],
    examples: ["Coverage/accuracy curves"],
    pitfalls: ["No coverage tracking"],
  },
  {
    term: "Policy-as-code",
    definition: "Policies captured in structured, versioned files enforced at runtime.",
    synonyms: ["PaC"],
    relatedLessons: ["requirements-policy-as-code"],
    examples: ["YAML rules for tools"],
    pitfalls: ["Untested policies"],
  },
  {
    term: "ADR",
    definition: "Architecture Decision Record; documents decisions and consequences.",
    synonyms: ["decision log"],
    relatedLessons: ["requirements-adr"],
    examples: ["Add meta-critic ADR"],
    pitfalls: ["No rollback noted"],
  },
  {
    term: "Traceability",
    definition: "Linking goals to constraints to tests to telemetry.",
    synonyms: ["trace matrix"],
    relatedLessons: ["requirements-traceability"],
    examples: ["Goal->constraint->test->event"],
    pitfalls: ["Orphaned tests"],
  },
  {
    term: "Meta-monitor signal",
    definition: "Telemetry feature watched by the meta-monitor.",
    synonyms: ["watcher signal"],
    relatedLessons: ["foundations-core-loops"],
    examples: ["drift_psi"],
    pitfalls: ["Thresholdless signals"],
  },
  {
    term: "Meta-critic rule",
    definition: "Policy check applied to plans/actions.",
    synonyms: ["guard"],
    relatedLessons: ["architecture-interfaces-contracts"],
    examples: ["No tool if risk>0.7"],
    pitfalls: ["No enforcement"],
  },
  {
    term: "Safety policy engine",
    definition: "Runtime gate combining rules and models to block unsafe actions.",
    synonyms: ["safety gate"],
    relatedLessons: ["architecture-reference"],
    examples: ["Rule + classifier ensemble"],
    pitfalls: ["Single point of failure"],
  },
  {
    term: "Observability",
    definition: "Structured telemetry, traces, and logs to understand system state.",
    synonyms: [],
    relatedLessons: ["architecture-observability-audit"],
    examples: ["action_executed events"],
    pitfalls: ["Raw logs only"],
  },
  {
    term: "Audit log",
    definition: "Immutable record of decisions and actions with actors and policy versions.",
    synonyms: [],
    relatedLessons: ["architecture-observability-audit"],
    examples: ["Signed safety_block events"],
    pitfalls: ["Editable logs"],
  },
  {
    term: "Provenance",
    definition: "Source lineage for data or memory entries.",
    synonyms: ["lineage"],
    relatedLessons: ["architecture-memory-systems"],
    examples: ["Hashes + source ids"],
    pitfalls: ["Missing hashes"],
  },
  {
    term: "Memory quorum",
    definition: "Requirement for multiple signals/sources before write.",
    synonyms: ["write quorum"],
    relatedLessons: ["failure-memory-corruption"],
    examples: ["2 sources required"],
    pitfalls: ["Single noisy source"],
  },
  {
    term: "Knowledge freshness",
    definition: "Recency of knowledge base entries.",
    synonyms: ["staleness"],
    relatedLessons: ["metrics-dictionary"],
    examples: ["Freshness <14 days"],
    pitfalls: ["Stale KB"],
  },
  {
    term: "Red-team prompt",
    definition: "Adversarial input used to test safety.",
    synonyms: ["attack prompt"],
    relatedLessons: ["metrics-offline-eval"],
    examples: ["Prompt to leak PII"],
    pitfalls: ["Unsafe execution"],
  },
  {
    term: "Shadow mode",
    definition: "Running new policy without affecting users for comparison.",
    synonyms: ["dark launch"],
    relatedLessons: ["metrics-regression"],
    examples: ["Shadow policy in eval"],
    pitfalls: ["No logging"],
  },
  {
    term: "Canary",
    definition: "Small-traffic rollout to limit blast radius.",
    synonyms: ["staged rollout"],
    relatedLessons: ["metrics-regression"],
    examples: ["5% traffic canary"],
    pitfalls: ["No rollback plan"],
  },
  {
    term: "Recovery budget",
    definition: "Allowed time to recover before escalation.",
    synonyms: ["MTTR target"],
    relatedLessons: ["metrics-dictionary"],
    examples: ["Recover within 5s"],
    pitfalls: ["No tracking"],
  },
  {
    term: "Environment volatility",
    definition: "Measure of how quickly environment shifts.",
    synonyms: [],
    relatedLessons: ["control-drift-modeling"],
    examples: ["High volatility triggers stricter policies"],
    pitfalls: ["Ignoring leading indicators"],
  },
  {
    term: "Tool budget",
    definition: "Cost/latency budget for tools per session.",
    synonyms: [],
    relatedLessons: ["architecture-tooling-layer"],
    examples: ["$0.01 per request"],
    pitfalls: ["Unlimited spend"],
  },
  {
    term: "Escalation SLA",
    definition: "Time bound for human response after escalation.",
    synonyms: ["response target"],
    relatedLessons: ["human-hitl"],
    examples: ["5 min response"],
    pitfalls: ["Unowned"],
  },
  {
    term: "Selective logging",
    definition: "Filtering logs to avoid PII while retaining auditability.",
    synonyms: [],
    relatedLessons: ["architecture-observability-audit"],
    examples: ["Hash sensitive fields"],
    pitfalls: ["Over-filtering hides issues"],
  },
  {
    term: "Postmortem",
    definition: "Structured analysis after incident to add tests/policies.",
    synonyms: ["RCA"],
    relatedLessons: ["metrics-postmortems"],
    examples: ["Add regression test after jailbreak"],
    pitfalls: ["No actions"],
  },
  {
    term: "Learning velocity",
    definition: "Rate of meaningful improvements per iteration.",
    synonyms: [],
    relatedLessons: ["metrics-dictionary"],
    examples: ["1 metric uplift/week"],
    pitfalls: ["Counting vanity changes"],
  },
  {
    term: "Confidence UI",
    definition: "Interface showing calibrated confidence and risk.",
    synonyms: ["trust UI"],
    relatedLessons: ["human-trust-calibration"],
    examples: ["Bar with evidence links"],
    pitfalls: ["Always green"],
  },
  {
    term: "Adaptation budget",
    definition: "Limit on number of self-modifications per time.",
    synonyms: ["change budget"],
    relatedLessons: ["control-meta-control-policies"],
    examples: ["3 policy changes/week"],
    pitfalls: ["Unlimited updates"],
  },
  {
    term: "Knowledge graph",
    definition: "Graph connecting terms, lessons, patterns, failures.",
    synonyms: [],
    relatedLessons: ["search"],
    examples: ["Visualization of MCSE links"],
    pitfalls: ["Unmaintained links"],
  },
  {
    term: "Practice mode",
    definition: "Lesson view showing exercises/quizzes only.",
    synonyms: [],
    relatedLessons: ["learn"],
    examples: ["Toggle in lesson UI"],
    pitfalls: ["Forgetting context"],
  },
  {
    term: "Artifact library",
    definition: "Local store of generated specs/policies.",
    synonyms: [],
    relatedLessons: ["studio"],
    examples: ["Saved YAML in IndexedDB"],
    pitfalls: ["No export/import"],
  },
  {
    term: "Knowledge freshness SLA",
    definition: "Target age for KB entries before refresh.",
    synonyms: ["staleness SLA"],
    relatedLessons: ["metrics-dictionary"],
    examples: ["Refresh critical KB every 14 days"],
    pitfalls: ["Untracked freshness"],
  },
  {
    term: "Red-team lab",
    definition: "Controlled environment to run adversarial prompts and record mitigations.",
    synonyms: [],
    relatedLessons: ["labs"],
    examples: ["Failure mode lab module"],
    pitfalls: ["Unsafe prompts"],
  },
  {
    term: "Knowledge export",
    definition: "JSON bundle of progress/artifacts for local-first backup.",
    synonyms: [],
    relatedLessons: ["progress"],
    examples: ["Download progress JSON"],
    pitfalls: ["Missing artifacts"],
  },
];
