import { Pattern } from "@/lib/types";

export const patterns: Pattern[] = [
  {
    name: "Guarded Self-Update",
    intent: "Prevent runaway self-modification.",
    whenToUse: "Any adaptive policy/model updates.",
    consequences: "Controlled evolution, slower updates.",
    implementationNotes: "Change budgets, approvals, tests before deploy.",
    antiPatterns: ["Unbounded self-change"],
    relatedFailures: ["failure-feedback-amplification"],
  },
  {
    name: "Dual Safety Layer",
    intent: "Defense-in-depth for safety decisions.",
    whenToUse: "High-risk actions/tools.",
    consequences: "Fewer false negatives, extra latency.",
    implementationNotes: "Rule + model ensemble, disagree -> block.",
    antiPatterns: ["Single safety gate"],
    relatedFailures: ["failure-tool-misuse"],
  },
  {
    name: "Selective Prediction",
    intent: "Abstain when uncertain.",
    whenToUse: "High-risk outputs.",
    consequences: "Higher precision, lower coverage.",
    implementationNotes: "Confidence thresholds per risk class.",
    antiPatterns: ["Blind autonomy"],
    relatedFailures: ["failure-miscalibration"],
  },
  {
    name: "Provenance-First Memory",
    intent: "Keep memory trustworthy.",
    whenToUse: "Any RAG/memory writes.",
    consequences: "Rollbackable, slower writes.",
    implementationNotes: "Hashes, confidence thresholds, snapshots.",
    antiPatterns: ["Memory wild west"],
    relatedFailures: ["failure-memory-corruption"],
  },
  {
    name: "Canary Then Rollout",
    intent: "Limit blast radius for changes.",
    whenToUse: "Deploying new policies/models.",
    consequences: "Safer rollouts, slower speed.",
    implementationNotes: "5% traffic, rollback triggers.",
    antiPatterns: ["Deploy to all"],
    relatedFailures: ["failure-feedback-amplification"],
  },
  {
    name: "Shadow Mode",
    intent: "Evaluate new logic without user impact.",
    whenToUse: "Testing new policies.",
    consequences: "Higher confidence before rollout.",
    implementationNotes: "Log comparisons, compute deltas.",
    antiPatterns: ["Eval once"],
    relatedFailures: ["failure-miscalibration"],
  },
  {
    name: "Adversarial-in-the-Loop",
    intent: "Continuously test safety with red-team cases.",
    whenToUse: "Safety-critical systems.",
    consequences: "Higher resilience.",
    implementationNotes: "Weekly red-team bank, auto reports.",
    antiPatterns: ["No drift watch"],
    relatedFailures: ["failure-reward-hacking"],
  },
  {
    name: "Confidence-Aware UX",
    intent: "Calibrate human trust.",
    whenToUse: "User-facing outputs.",
    consequences: "Better trust, possible slower decisions.",
    implementationNotes: "Show confidence + evidence + fallback.",
    antiPatterns: ["Trust inflation UI"],
    relatedFailures: ["failure-feedback-amplification"],
  },
  {
    name: "Budgeted Tooling",
    intent: "Control cost/risk of tool calls.",
    whenToUse: "Expensive or risky tools.",
    consequences: "Predictable spend.",
    implementationNotes: "Per-session budgets, rate limits.",
    antiPatterns: ["Tool free-for-all"],
    relatedFailures: ["failure-tool-misuse"],
  },
  {
    name: "Policy-as-Code",
    intent: "Testable policies.",
    whenToUse: "Safety/guardrails.",
    consequences: "Auditability, CI hooks.",
    implementationNotes: "YAML/JSON policies + tests.",
    antiPatterns: ["Untested policies"],
    relatedFailures: ["failure-reward-hacking"],
  },
  {
    name: "Postmortem-to-Playbook",
    intent: "Turn incidents into runbooks and tests.",
    whenToUse: "After any incident.",
    consequences: "Learning velocity up.",
    implementationNotes: "Update playbook + regression tests automatically.",
    antiPatterns: ["Postmortem theater"],
    relatedFailures: ["failure-memory-corruption"],
  },
  {
    name: "Drift-Sim Sandbox",
    intent: "Surface failures before production.",
    whenToUse: "Facing shifts/seasonality.",
    consequences: "Better preparedness.",
    implementationNotes: "Simulate shifts, run harness + safety tests.",
    antiPatterns: ["No drift watch"],
    relatedFailures: ["failure-feedback-amplification"],
  },
];
